### ISSUE TITLE
Review splash page and user auth MVP#1

### ISSUE THREAD

**Issue by rfoong8983** [rfoong8983/disclone#2]
https://disclone-rf.herokuapp.com/#/

Hi Liz, I've finished my first mvp (or so I think)- Let me know what you think! Appreciate the guidance and feedback as always c:

 - I currently do not have a visible sign-out button because on log-in, the user should be redirected to the application route. 
 - I set my app to redirect to the homepage for now. 
 - After login, you'll be redirected to homepage however you will not be able to go to the sign-up or log-in or demo-login because I'm using auth-routes. 
 - To sign-out and test other things, you may click the logo (which has been rigged to sign-out).
 - There is no link to the homepage from the login/register screen on Discord's app so I made MY logo clickable and it will redirect you to the homepage.

- [x] Splash page has link to demo the chat-app, sign-up/sign-in
- [x] Users can sign-up, sign-in, and sign-out
- [x] Users can use demo-login to experience the site
- [x] Users can't access features (joining & creating servers, etc.) without signing in
- [x] Smooth, bug-free navigation (-ish, check my comments above)
- [x] Adequate styling

**Comment by eshoule** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [ ] Should be able to refresh the page and still be logged in


## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by rfoong8983** [comment]
@eshoule I will come back and fix the logo positioning for login/signup page

**Comment by rfoong8983** [comment]
@eshoule I fixed the logo on the login/signup page- the form now takes precedence over it
